Release/1.4.1
ondewo/ondewo-s2t-client-angular pull request #2
Opened 2021-05-11 12:12 UTC by Phips0812

2021-05-11 13:11 UTC, gaborod16 requested changes
Just a string change in the package.json file.
The rest looks consistent to its nature and purpose :)

2021-05-11 13:11 UTC, gaborod16 commented on .gitmodules
> +	branch = release/1.4.0
Oh!
I see what the problem was before!

Yes, tag are sadly not supported.

2021-05-11 13:11 UTC, gaborod16 commented on RELEASE.md
> +* Upgraded from ngx-grpc 0.3.1 to 2.1.0
:+1:

2021-05-11 13:11 UTC, gaborod16 commented on package.json
> +  "description": "Ondewo natural language understanding client library for angular",
Gotcha!
This is the Speech-to-Text client, not NLU :)

2021-05-12 07:42 UTC, Phips0812 commented
Requested changes implemented -> Merging

2021-05-12 07:43 UTC, merged